name: CI Test Multi-Node

on:
  pull_request:
    branches: [ master, '**-dev' ]
  push:
    branches: [ 'feature/**', 'hotfix/**']

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04]
        compiler: [g++-14]
        mpi-type: [openmpi]
        build-type: [Release]
    env:
      FLUX_VERSION: 0.81.0
      SPACK_DIR: "/home/runner/work/spack"
      FLUX_DIR: "/home/runner/work/flux"
      FLUX_DOWNLOAD_URL: "https://github.com/flux-framework/flux-core/releases/download/"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Update apt
        run: |
          sudo add-apt-repository -y universe
          sudo apt-get update
      - name: Cache boost
        uses: actions/cache@v4
        id: cache-boost
        with:
          path: "~/boost_1_81_0"
          key: ${{ runner.os }}-libboost1.81
      - name: Install boost
        if: steps.cache-boost.outputs.cache-hit != 'true'
        run: |
          cd ~
          wget --no-verbose https://archives.boost.io/release/1.81.0/source/boost_1_81_0.tar.bz2
          tar -xjf boost_1_81_0.tar.bz2
      - name: Install mpich
        if: matrix.mpi-type == 'mpich'
        run: sudo apt-get install mpich
      - name: Install OpenMPI
        if: matrix.mpi-type == 'openmpi'
        run: sudo apt-get install openmpi-bin libopenmpi-dev
      - name: Install GCC
        if: (matrix.compiler == 'g++-11' && matrix.os == 'ubuntu-24.04')
        run: sudo apt-get install gcc-11 g++-11
#      - name: Install Spack
#        run: |
#          git clone --depth=2 https://github.com/spack/spack.git ${SPACK_DIR}
#          . ${SPACK_DIR}/share/spack/setup-env.sh
#          spack compiler find --scope=user
#      - name: Instal flux
#        run: |
#          . ${SPACK_DIR}/share/spack/setup-env.sh
#          spack install -j4 flux-core@${FLUX_VERSION}
      - name: Install flux from source
        run: |
          mkdir ${FLUX_DIR}
          cd ${FLUX_DIR}
          wget "${FLUX_DOWNLOAD_URL}/v${FLUX_VERSION}/flux-core-${FLUX_VERSION}.tar.gz"
          tar -xzvf flux-core-${FLUX_VERSION}.tar.gz
          cd flux-core-${FLUX_VERSION}
          sudo ./scripts/install-deps-deb.sh
          ./autogen.sh
          ./configure
          make -j4
          ./src/cmd/flux start --test-size=16
#      - name: Make
#        run: |
#          echo Run 'make'
#          mpicc -show
#          ${{ matrix.compiler }} --version
#          mkdir build
#          cd build
#          cmake ../ -DYGM_BUILD_TESTS=On -DCMAKE_BUILD_TYPE=${{ matrix.build-type }} -DCMAKE_CXX_COMPILER=${{ matrix.compiler }} -DBOOST_ROOT=~/boost_1_81_0 -DYGM_INSTALL_PARQUET=ON
#          make -j4
#      - name: Make test (mpich)
#        if: matrix.mpi-type == 'mpich'
#        run: |
#          echo Run 'make test' with mpich, ${{ matrix.compiler }}
#          cd build
#          ctest -VV -C ${{ matrix.build-type }}
#      - name: Make test (OpenMPI)
#        if: matrix.mpi-type == 'openmpi'
#        run: |
#          echo Run 'make test' with OpenMPI, ${{ matrix.compiler }}
#          cd build
#          export OMPI_MCA_rmaps_base_oversubscribe=1
#          ctest -VV -C ${{ matrix.build-type }}
